services:
  - type: web
    name: blue-bunny-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 backend/main.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # You'll add it securely via Render dashboard
